#!/bin/bash
  
source 0.env.sh

while read -r line; 
    do 
      declare $line; 
      printf "Adding VM %s of size %s with publicIP " $vmName $vmSize; 
           [[ -z $publicIPName ]] && { printf "none "; } || { printf "%s " $publicIPName; }; 
           [[ -z $networkSecurityGroup ]] && { printf "NetworkSecurityGroup autogenerated\n"; } || { printf "NetworkSecurityGroup %s\n" $networkSecurityGroup; };
      
     if [ ! -z $publicIPName ]
     then
       source 2a.createHostWithPublicIPandNSG.sh
     else
       source 2b.createHost.sh
     fi 
    done < hostsinfo.txt

source 3.getHostIPAddresses.sh
